### ISSUE TITLE
Plugin won't load in latest Homebridge

### ISSUE THREAD

**Issue by kanzelsberger** [msteitz/homebridge-octoprint-connect#5]
This is the error inconsole:

`Error [ERR_REQUIRE_ESM]: require() of ES Module /usr/lib/node_modules/homebridge-octoprint-temp/node_modules/got/dist/source/index.js from /usr/lib/node_modules/homebridge-octoprint-temp/index.js not supported.
Instead change the require of /usr/lib/node_modules/homebridge-octoprint-temp/node_modules/got/dist/source/index.js in /usr/lib/node_modules/homebridge-octoprint-temp/index.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/usr/lib/node_modules/homebridge-octoprint-temp/index.js:1:11)
    at Plugin.load (/usr/lib/node_modules/homebridge/lib/plugin.js:132:77)
    at PluginManager.initializeInstalledPlugins (/usr/lib/node_modules/homebridge/lib/pluginManager.js:64:30)
    at async Server.start (/usr/lib/node_modules/homebridge/lib/server.js:106:9)`

**Comment by ixy05** [comment]
i get this too.

**Comment by Berlinologe86** [comment]
same here 👍 

21/01/2022, 17:48:31] No plugin was found for the accessory "Octoprint-Temp" in your config.json. Please make sure the corresponding plugin is installed correctly.


[21/01/2022, 17:48:30] ====================
[21/01/2022, 17:48:30] ERROR LOADING PLUGIN homebridge-octoprint-temp:
[21/01/2022, 17:48:30] Error [ERR_REQUIRE_ESM]: require() of ES Module /usr/lib/node_modules/homebridge-octoprint-temp/node_modules/got/dist/source/index.js from /usr/lib/node_modules/homebridge-octoprint-temp/index.js not supported.
Instead change the require of /usr/lib/node_modules/homebridge-octoprint-temp/node_modules/got/dist/source/index.js in /usr/lib/node_modules/homebridge-octoprint-temp/index.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/usr/lib/node_modules/homebridge-octoprint-temp/index.js:1:11)
    at Plugin.load (/usr/lib/node_modules/homebridge/lib/plugin.js:135:108)
    at PluginManager.initializeInstalledPlugins (/usr/lib/node_modules/homebridge/lib/pluginManager.js:64:30)
    at async Server.start (/usr/lib/node_modules/homebridge/lib/server.js:106:9)
[21/01/2022, 17:48:30] ====================

**Comment by msteitz** [comment]
Thank you all for bringing this up and sorry for the late reply. I updated the code based on the proposal.

**Comment by skwasimo** [comment]
Hi, same problem still existing. Did the code get updated?
